# Generated by Django 5.1.7 on 2025-03-25 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
