# Generated by Django 5.1.7 on 2025-03-25 06:58

from django.db import migrations, models

import diary.models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_diary_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(default=diary.models.get_today_date),
        ),
    ]
