# Generated by Django 5.1.7 on 2025-03-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
