# Generated by Django 5.1.7 on 2025-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0005_alter_member_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="nickname",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
