# Generated by Django 5.1.7 on 2025-03-18 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0006_alter_member_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
