# Generated by Django 5.1.7 on 2025-03-18 17:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0007_alter_socialaccount_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="favorite_genre",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="introduce",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
