# Generated by Django 5.1.7 on 2025-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "member",
            "0008_alter_member_favorite_genre_alter_member_introduce_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="nickname",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
